# NUMPY ASSIGNMENT

# Problem 1

In [22]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.59171134 0.31452748 0.84591489]
  [0.62888698 0.20761812 0.85523981]
  [0.84221613 0.82639649 0.46926621]]

 [[0.5603882  0.37630473 0.87981439]
  [0.28857469 0.84874473 0.52584293]
  [0.52801734 0.01975364 0.30217697]]

 [[0.69279689 0.2047477  0.18587442]
  [0.13848019 0.32991207 0.70289273]
  [0.46286167 0.91153019 0.55420138]]]


# problem 2

In [2]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]



# Problem 3

In [11]:
import numpy as np

print("Checkerboard pattern of 8 cross 8:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern of 8 cross 8:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem 4

In [13]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.21710805 0.74047299 0.35049003 0.30399806 0.72790135]
 [0.3867996  0.58688861 0.98786189 0.74778883 0.30899131]
 [0.96532416 0.23862845 0.65374872 0.30642648 0.86466097]
 [0.56322292 0.73655494 0.21696126 0.30941761 0.0070238 ]
 [0.06424145 0.37732353 0.29695476 0.51192493 0.0540826 ]]
After normalization:
[[0.21418851 0.74777804 0.35017627 0.30277602 0.7349608 ]
 [0.38719519 0.5911932  1.         0.75523681 0.30786682]
 [0.97702196 0.23612934 0.6593595  0.30525189 0.87439219]
 [0.56706516 0.74378345 0.21403885 0.30830145 0.        ]
 [0.05833547 0.377534   0.29559513 0.51476501 0.04797815]]


# Problem 5

In [17]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print(type(array1))
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


<class 'numpy.ndarray'>
Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# Problem 6

In [18]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# Problem 7

In [19]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[0 0 1 1 0 1]
Second array:
[1 0 0 1 0 0]
Test above two arrays are equal or not!
False


# Problem 8

In [23]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[0.60849622 0.98603764 0.83422594 0.62406613 0.61933307 0.54198323
 0.09610252 0.1016936  0.17451269 0.73727074]
Maximum value replaced by 0:
[0.60849622 0.         0.83422594 0.62406613 0.61933307 0.54198323
 0.09610252 0.1016936  0.17451269 0.73727074]


# Problem 9

In [32]:
import numpy as np
import sys
nums = np.arange(2000)
np.set_printoptions(threshold=sys.maxsize)
print(nums)


[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

# Problem 10

In [57]:
import numpy as np
X = np.random.rand(50, 100)
A=X.mean(axis=1, keepdims=True).reshape(-1,1)
A.shape
Y = X -A


# Problem 11

In [3]:
def sum(arr, n): 
  
    i = n 
    if(arr[i] < 9): 
      
        arr[i] = arr[i] + 1
        return
    arr[i] = 0
    i -= 1
    sum(arr, i) 
      
n = 4
arr = [0, 1, 9, 3, 9] 
  
sum(arr, n) 
if(arr[0] > 0): 
    print(arr[0], ", ", end="") 
      
for i in range(1, n+1): 
      
    print(arr[i], end="") 
    if(i < n): 
        print(", ", end="") 

1, 9, 4, 0

# Problem 12

In [63]:
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)
print(np.diag(np.dot(np.dot(a, b), a.T)))
print(np.einsum('ij,ji->i', np.dot(a, b), a.T))
print(np.einsum('ij,ij->i', np.dot(a, b), a))

[  60  672 1932 3840 6396]
[  60  672 1932 3840 6396]
[  60  672 1932 3840 6396]


# Problem 13 

In [64]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[6 8 9 3 6 6 0 0 6 2 7 1 0 5 6 9 5 4 7 3 6 7 1 9 5 7 3 3 8 6 3 0 3 8 2 3 9
 7 5 1]
Most frequent value in the above array:
3


# Problem 14

In [1]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# Problem 15

In [2]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
